#!/bin/bash

PID_FILE="/var/run/my_process.pid"
SCRIPT="./manage_my_process"

start_process() {
    $SCRIPT &
    echo $! > $PID_FILE
    echo "$SCRIPT started"
}

stop_process() {
    if [ -e $PID_FILE ]; then
        PID=$(cat $PID_FILE)
        kill $PID
        rm -f $PID_FILE
        echo "$SCRIPT stopped"
    else
        echo "$SCRIPT is not running"
    fi
}

restart_process() {
    stop_process
    start_process
    echo "$SCRIPT restarted"
}

case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

